### ISSUE TITLE
Question about null error when reading entry after build.

### ISSUE THREAD

**Issue by Chris-DuCharme** [davidhellmann/craftcms-baukasten-headless#14]
I stumbled upon this repo googling for tutorials on how to set up Craft CMS with Nuxt 3 and used it as a starting point to make my own playground to learn how to develop using Nuxt 3 with Craft.

One big difference is instead of content builder approach you took, I went with the Neo Plugin to create my bocks and called the Vue components by the typeHandle.  

Everything is working in `npm run dev` and pages are fully rendering without any errors being logged to console.  However, as soon as I run `npm run build` and then `npm run preview` most pages are broken.  Only the header and footer show after a quick flash of the body content.  Console logs the following error: 

```TypeError: Cannot read properties of null (reading 'entry') at setup (_...uri_.7afa0285.js:1:1290)```

I haven't figured out how to get a more specific error to try to pinpoint what's causing it and I've been stuck on this for a couple weeks now.

I was wondering if this was an error you were seeing as well or if you might have any insights into it and where to start troubleshooting.

Thanks,
Chris

**Comment by davidhellmann** [comment]
Hey Chris,

nice to see you here. But to be honest. Most of the time I play locally without building at the moment. But it sounds like an async/await topic and there is no await for your fetch or something like that on build? 🤔

**Comment by Chris-DuCharme** [comment]
Hey David, 

Thanks for the reply.

I don't think it's a async/await issue as the page is fully visible for a second before the error is triggered.

I think I am on to something tonight.  Accessing the page via a Nuxt Link renders the page.  Gong directly to the page errors.  

At a closer inspection I noticed the different is a trailing slash.  With the Nuxt Link, I end up on a page like so `domain.com/about` where as if I type that same domain in the address bar and hit enter I land on `domain.com/about/`

The Nuxt router appears to load the page, which is why I see the quick flash, and then redirect to the same page with the trailing slash that errors when the content reloads.  

I'm going to sleep on it and continue investigating in the morning.

**Comment by davidhellmann** [comment]
OK, interesting. Let me know if you figured it out what was the problem.

**Comment by Chris-DuCharme** [comment]
I've got it figured out.

I had apparently solved the issue when previewing the build locally but didn't realize it as the issue was still present in my Netlify Sandbox.

This was my issue: https://support.gatsbyjs.com/hc/en-us/articles/360056349113-Remove-trailing-slash-in-Netlify-URLs

Disabling the "Pretty URLs" resolved the trailing slash issue and now the build is working as intended.
